// <auto-generated />
using System;
using BookingFlightService.BookingFlightDAL.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingFlightDAL.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20230107145441_CreateSeatDB")]
    partial class CreateSeatDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingFlightDAL.Models.Seat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Place = "1A"
                        },
                        new
                        {
                            ID = 2,
                            Place = "1B"
                        },
                        new
                        {
                            ID = 3,
                            Place = "1C"
                        },
                        new
                        {
                            ID = 4,
                            Place = "1D"
                        },
                        new
                        {
                            ID = 5,
                            Place = "1E"
                        },
                        new
                        {
                            ID = 6,
                            Place = "1F"
                        },
                        new
                        {
                            ID = 7,
                            Place = "2A"
                        },
                        new
                        {
                            ID = 8,
                            Place = "2B"
                        },
                        new
                        {
                            ID = 9,
                            Place = "2C"
                        },
                        new
                        {
                            ID = 10,
                            Place = "2D"
                        },
                        new
                        {
                            ID = 11,
                            Place = "2E"
                        },
                        new
                        {
                            ID = 12,
                            Place = "2F"
                        },
                        new
                        {
                            ID = 13,
                            Place = "3A"
                        },
                        new
                        {
                            ID = 14,
                            Place = "3B"
                        },
                        new
                        {
                            ID = 15,
                            Place = "3C"
                        },
                        new
                        {
                            ID = 16,
                            Place = "3D"
                        },
                        new
                        {
                            ID = 17,
                            Place = "3E"
                        },
                        new
                        {
                            ID = 18,
                            Place = "3F"
                        },
                        new
                        {
                            ID = 19,
                            Place = "4A"
                        },
                        new
                        {
                            ID = 20,
                            Place = "4B"
                        },
                        new
                        {
                            ID = 21,
                            Place = "4C"
                        },
                        new
                        {
                            ID = 22,
                            Place = "4D"
                        },
                        new
                        {
                            ID = 23,
                            Place = "4E"
                        },
                        new
                        {
                            ID = 24,
                            Place = "4F"
                        },
                        new
                        {
                            ID = 25,
                            Place = "5A"
                        },
                        new
                        {
                            ID = 26,
                            Place = "5B"
                        },
                        new
                        {
                            ID = 27,
                            Place = "5C"
                        },
                        new
                        {
                            ID = 28,
                            Place = "5D"
                        },
                        new
                        {
                            ID = 29,
                            Place = "5E"
                        },
                        new
                        {
                            ID = 30,
                            Place = "5F"
                        },
                        new
                        {
                            ID = 31,
                            Place = "6A"
                        },
                        new
                        {
                            ID = 32,
                            Place = "6B"
                        },
                        new
                        {
                            ID = 33,
                            Place = "6C"
                        },
                        new
                        {
                            ID = 34,
                            Place = "6D"
                        },
                        new
                        {
                            ID = 35,
                            Place = "6E"
                        },
                        new
                        {
                            ID = 36,
                            Place = "6F"
                        },
                        new
                        {
                            ID = 37,
                            Place = "7A"
                        },
                        new
                        {
                            ID = 38,
                            Place = "7B"
                        },
                        new
                        {
                            ID = 39,
                            Place = "7C"
                        },
                        new
                        {
                            ID = 40,
                            Place = "7D"
                        },
                        new
                        {
                            ID = 41,
                            Place = "7E"
                        },
                        new
                        {
                            ID = 42,
                            Place = "7F"
                        },
                        new
                        {
                            ID = 43,
                            Place = "8A"
                        },
                        new
                        {
                            ID = 44,
                            Place = "8B"
                        },
                        new
                        {
                            ID = 45,
                            Place = "8C"
                        },
                        new
                        {
                            ID = 46,
                            Place = "8D"
                        },
                        new
                        {
                            ID = 47,
                            Place = "8E"
                        },
                        new
                        {
                            ID = 48,
                            Place = "8F"
                        },
                        new
                        {
                            ID = 49,
                            Place = "9A"
                        },
                        new
                        {
                            ID = 50,
                            Place = "9B"
                        },
                        new
                        {
                            ID = 51,
                            Place = "9C"
                        },
                        new
                        {
                            ID = 52,
                            Place = "9D"
                        },
                        new
                        {
                            ID = 53,
                            Place = "9E"
                        },
                        new
                        {
                            ID = 54,
                            Place = "9F"
                        },
                        new
                        {
                            ID = 55,
                            Place = "10A"
                        },
                        new
                        {
                            ID = 56,
                            Place = "10B"
                        },
                        new
                        {
                            ID = 57,
                            Place = "10C"
                        },
                        new
                        {
                            ID = 58,
                            Place = "10D"
                        },
                        new
                        {
                            ID = 59,
                            Place = "10E"
                        },
                        new
                        {
                            ID = 60,
                            Place = "10F"
                        });
                });

            modelBuilder.Entity("BookingFlightService.BookingFlightDAL.Models.Booking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
